services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_CONNECTION_USERNAME:-root}
      POSTGRES_PASSWORD: ${DB_CONNECTION_PASSWORD:-defaultpassword}
      POSTGRES_DB: ${DB_NAME:-postgres}
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U ${DB_CONNECTION_USERNAME:-root} -d ${DB_NAME:-postgres}'" ]
      interval: 10s
      timeout: 10s
      retries: 5